platform :ios, ‘7.1’
pod "AFNetworking", "~> 2.6.0”
platform :ios, ‘7.1’
pod "IQKeyboardManager", "~> 3.3.1”
platform :ios, ‘7.1’
pod 'MJExtension', '~> 2.5.10'
platform :ios, ‘7.1’
pod 'MBProgressHUD', '~> 0.9.1'
platform :ios, ‘7.1’
pod 'SDWebImage', '~> 3.7.3'
